# azure-pipelines.validate.yml
pr:
  branches:
    include:
      - main

pool:
  name: LeonelAgent

variables:
  packagePath: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(packagePath)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(packagePath)'
    artifactName: 'drop'
    publishLocation: 'Container'