trigger:
  branches:
    include:
      - main

pool:
  name: LeonelAgent

variables:
  azureSubscription: 'FinancierosGR-Connection'
  appName: 'GestionOrdenes'

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(Pipeline.Workspace)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(Pipeline.Workspace)/a/publish/**/*.zip'