pr:
  branches:
    include:
      - main

pool:
  name: LeonelAgent

variables:
  azureSubscription: 'FinancierosGR-Connection'
  appName: 'GestionOrdenes'
  packagePath: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- checkout: self  # ✅ AGREGAR ESTA LÍNEA AL INICIO
  displayName: 'Checkout source code'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(packagePath)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(packagePath)'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(Pipeline.Workspace)/a/publish/*.zip'