trigger:
  branches:
    include:
      - main

pool:
  name: LeonelAgent

variables:
  azureSubscription: 'FinancierosGR-Connection'
  appName: 'GestionOrdenes'
  pipelineId: '2'  # ID del pipeline que genera el artefacto

steps:
- checkout: self
  displayName: 'Checkout source code'

- powershell: |
    $organization = "leonel820906"
    $project = "GestionOrdenes"
    $pipelineId = "$(pipelineId)"
    $uri = "https://dev.azure.com/$organization/$project/_apis/build/builds?definitions=$pipelineId&statusFilter=completed&resultFilter=succeeded&$top=1&api-version=7.1-preview.7"

    $headers = @{
      Authorization = "Bearer $(System.AccessToken)"
    }

    $response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get
    if ($response.count -eq 0) {
      Write-Error "No se encontró ningún build exitoso para el pipeline ID $pipelineId"
      exit 1
    }

    $buildVersion = $response.value[0].buildNumber
    Write-Host "Último build exitoso: $buildVersion"
    Write-Host "##vso[task.setvariable variable=buildVersion]$buildVersion"
  displayName: 'Obtener último build exitoso'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'GestionOrdenes'
    definition: '$(pipelineId)'
    buildVersion: '$(buildVersion)'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)/drop'
  displayName: 'Descargar artefacto del último build exitoso'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(Pipeline.Workspace)/drop/publish/**/*.zip'
  displayName: 'Desplegar a Azure App Service'