trigger:
  branches:
    include:
      - main

pool:
  name: LeonelAgent

variables:
  azureSubscription: 'FinancierosGR-Connection'
  appName: 'GestionOrdenes'

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: drop
    path: '$(Pipeline.Workspace)/drop'
    buildType: 'latest'
    targetPath: '$(Pipeline.Workspace)/drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(Pipeline.Workspace)/drop/publish/**/*.zip'